USE RBAC
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[OrgAllowIP](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[OrgID] [int] NOT NULL,
	[IpStart] [varchar](40) NOT NULL,
	[IpEnd] [varchar](40) NOT NULL,
	[LogicDel] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[OrgAllowIP] ADD  DEFAULT ((0)) FOR [OrgID]
GO

ALTER TABLE [dbo].[OrgAllowIP] ADD  DEFAULT ('') FOR [IpStart]
GO

ALTER TABLE [dbo].[OrgAllowIP] ADD  DEFAULT ('') FOR [IpEnd]
GO

ALTER TABLE [dbo].[OrgAllowIP] ADD  DEFAULT ((0)) FOR [LogicDel]
GO


