USE RBAC
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PowerCate](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PowerCateName] [nvarchar](20) NOT NULL,
	[PowerCateIndex] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PowerCate] ADD  DEFAULT ('') FOR [PowerCateName]
GO

ALTER TABLE [dbo].[PowerCate] ADD  DEFAULT ((0)) FOR [PowerCateIndex]
GO


