USE RBAC
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PowerType](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PowerName] [nvarchar](20) NOT NULL,
	[PowerIndex] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PowerType] ADD  DEFAULT ('') FOR [PowerName]
GO

ALTER TABLE [dbo].[PowerType] ADD  DEFAULT ((0)) FOR [PowerIndex]
GO


